### PR TITLE
Add Golden Seeds

### PR DESCRIPTION
**Pull request by RDoll-Repo**
Issue: https://github.com/Gobluebro/Elden-Ring-Checklist/issues/37

This PR adds a checklist for golden seeds. Fextra seemed like the most complete source of seeds, as is expected for FromSoft titles. [This](https://eldenring.wiki.fextralife.com/Golden+Seed) is the list I referenced, and the seeds are grouped accordingly. That being said, this page actually contains quite a few duplicate seeds. IE: Video Location bulletpoints in the list are dupes of other bulletpoints and the one seed in the "Miquella's Haligtree" section is already covered in the "Elphael" section, so I have omitted those. 

As discussed in the corresponding issue, the idea is to describe seeds distinctly enough to allow users to identify seeds they have collected, and not necessarily walk them through from point A to point B. If there is a particular seed we feel is perhaps too vague, I'm more than happy to make adjustments.

The general template I used for each entry is:
`Nearest Applicable Landmark: Terse Description of the Seed relative to it`
I have made a few exceptions to this template for seeds I felt were not quite facilitative to it.

### CODE REVIEW

**Comment by Gobluebro** [comment]
I may take some time to look into this throughout the week. Thank you for your patience

**Comment by Gobluebro** [comment]
> https://github.com/Gobluebro/Elden-Ring-Checklist/issues/37 is the list I referenced, and the seeds are grouped accordingly. That being said, this page actually contains quite a few duplicate seeds. IE: Video Location bulletpoints in the list are dupes of other bulletpoints and the one seed in the "Miquella's Haligtree" section is already covered in the "Elphael" section, so I have omitted those.

I think you accidentally copy and pasted the same url as the original issue page. Can you link me the site you are talking about?

**Comment by RDoll-Repo** [comment]
> > #37 is the list I referenced, and the seeds are grouped accordingly. That being said, this page actually contains quite a few duplicate seeds. IE: Video Location bulletpoints in the list are dupes of other bulletpoints and the one seed in the "Miquella's Haligtree" section is already covered in the "Elphael" section, so I have omitted those.
> 
> I think you accidentally copy and pasted the same url as the original issue page. Can you link me the site you are talking about?

🤦 I sure did. Whoops. Here's the actual link:
https://eldenring.wiki.fextralife.com/Golden+Seed

(Updated in the description as well for future passerby)

**Comment by Gobluebro** [comment]
I think I managed to look at everything that I wanted to. Let me know if you have any questions for my changes.

**Review by Gobluebro — APPROVED** [review]
LGTM. Happy to sneak some much needed code changes in this one.

**Pull request merged**
